const asyncHandler = require("express-async-handler");
const JournalEntry = require("../models/JournalEntry");
const { analyzeJournalEntry } = require("../utils/geminiService");
const { rangeForPeriod } = require("../utils/dateHelpers");

const createJournal = asyncHandler(async (req, res) => {
  const { title, content, voiceNoteUrl, date, isPrivate } = req.body;
  if (!content || !content.trim()) {
    res.status(400);
    throw new Error("Journal content is required");
  }

  const entry = await JournalEntry.create({
    user: req.user._id,
    title,
    content,
    voiceNoteUrl,
    isPrivate: isPrivate !== undefined ? isPrivate : true,
    date: date || Date.now(),
  });

  res.status(201).json({ success: true, entry });
});

const getJournals = asyncHandler(async (req, res) => {
  const { period } = req.query;
  const query = { user: req.user._id };
  if (period) {
    const { start, end } = rangeForPeriod(period);
    query.date = { $gte: start, $lte: end };
  }
  const entries = await JournalEntry.find(query).sort({ date: -1 });
  res.json({ success: true, count: entries.length, entries });
});

const getJournalById = asyncHandler(async (req, res) => {
  const entry = await JournalEntry.findOne({ _id: req.params.id, user: req.user._id });
  if (!entry) {
    res.status(404);
    throw new Error("Journal entry not found");
  }
  res.json({ success: true, entry });
});

const updateJournal = asyncHandler(async (req, res) => {
  const entry = await JournalEntry.findOne({ _id: req.params.id, user: req.user._id });
  if (!entry) {
    res.status(404);
    throw new Error("Journal entry not found");
  }
  const { title, content, voiceNoteUrl, isPrivate } = req.body;
  if (title !== undefined) entry.title = title;
  if (content !== undefined) entry.content = content;
  if (voiceNoteUrl !== undefined) entry.voiceNoteUrl = voiceNoteUrl;
  if (isPrivate !== undefined) entry.isPrivate = isPrivate;
  await entry.save();
  res.json({ success: true, entry });
});

const deleteJournal = asyncHandler(async (req, res) => {
  const entry = await JournalEntry.findOneAndDelete({ _id: req.params.id, user: req.user._id });
  if (!entry) {
    res.status(404);
    throw new Error("Journal entry not found");
  }
  res.json({ success: true, message: "Journal entry deleted" });
});

// @desc Run (or re-run) Gemini AI analysis on a journal entry
// @route POST /api/journal/:id/analyze
const analyzeJournal = asyncHandler(async (req, res) => {
  const entry = await JournalEntry.findOne({ _id: req.params.id, user: req.user._id });
  if (!entry) {
    res.status(404);
    throw new Error("Journal entry not found");
  }

  const analysis = await analyzeJournalEntry(entry.content);

  entry.aiAnalysis = {
    sentiment: analysis.sentiment,
    sentimentScore: analysis.sentimentScore,
    stressIndicators: analysis.stressIndicators || [],
    recurringThemes: analysis.recurringThemes || [],
    positiveHabits: analysis.positiveHabits || [],
    areasToImprove: analysis.areasToImprove || [],
    riskLevel: analysis.riskLevel || "none",
    analyzedAt: new Date(),
    disclaimer:
      "This is general wellness insight generated by AI, not a medical or psychological diagnosis.",
  };
  await entry.save();

  res.json({
    success: true,
    entry,
    suggestions: analysis.suggestions || [],
  });
});

module.exports = {
  createJournal,
  getJournals,
  getJournalById,
  updateJournal,
  deleteJournal,
  analyzeJournal,
};
