const mongoose = require("mongoose");

const journalEntrySchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    date: { type: Date, required: true, default: Date.now, index: true },
    title: { type: String, trim: true, maxlength: 150 },
    content: { type: String, required: true, maxlength: 10000 },
    voiceNoteUrl: { type: String, default: null }, // optional pre-signed/static URL
    isPrivate: { type: Boolean, default: true },

    // AI analysis cache (populated asynchronously by aiController)
    aiAnalysis: {
      sentiment: { type: String, enum: ["positive", "neutral", "negative", "mixed"], default: null },
      sentimentScore: { type: Number, min: -1, max: 1, default: null },
      stressIndicators: [{ type: String }],
      recurringThemes: [{ type: String }],
      positiveHabits: [{ type: String }],
      areasToImprove: [{ type: String }],
      riskLevel: { type: String, enum: ["none", "low", "moderate", "elevated"], default: "none" },
      analyzedAt: { type: Date, default: null },
      disclaimer: {
        type: String,
        default:
          "This is general wellness insight generated by AI, not a medical or psychological diagnosis.",
      },
    },
  },
  { timestamps: true }
);

journalEntrySchema.index({ user: 1, date: -1 });

module.exports = mongoose.model("JournalEntry", journalEntrySchema);
